FizzBuzzApp/FizzBuzzApp/Models/FizzBuzzModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace FizzBuzzApp.Models
{
    public class FizzBuzzModel
    {

        [Required]
        [Display(Name = "Input Value")]
        //For range validation
        [Range(1, 1000)]
        public  int InputValue { get; set; }
        public List<string> lstValue { get; set; }
    
    }
}

FizzBuzzApp/FizzBuzzApp/Controllers/FizzBuzzController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FizzBuzzApp.Models;
using FizzBuzzApp.Business;


namespace FizzBuzzApp.Controllers
{
    public class FizzBuzzController : Controller
    {
        //
        // GET: /FizzBuzz/

        public ActionResult Index()
        {
            FizzBuzzModel model = new FizzBuzzModel();
            return View(model);
        }

        public ActionResult ShowResult(FizzBuzzModel model)
        {
            if (ModelState.IsValid)
            {
                int txtval;
                txtval = model.InputValue;
                List<string> strValue = new List<string>();
                //Calling Business Logic to execute the values
                Logic retvalue = new Logic();
                strValue = retvalue.RetuenValue(txtval);
                model.lstValue = strValue;

            }
            return View("index", model);
        }

    }
}

FizzBuzzApp/FizzBuzzApp/Views/FizzBuzz/Index.cshtml
@model FizzBuzzApp.Models.FizzBuzzModel
@{
    ViewBag.Title = "Index";
}
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Display FizzBuzz</title>
    <style>
       
        
    </style>
 
 <script src="../../Scripts/jquery-1.7.1.min.js" type="text/javascript"></script>
 <script src="../../Scripts/Pagination.js" type="text/javascript"></script>
 <link href="../../CSS/Design.css" rel="stylesheet" type="text/css" />
</head>
   

<body>
    <div>
        Please Enter value :
        @using (Html.BeginForm("ShowResult", "FizzBuzz", FormMethod.Post))
        {
         
            @Html.TextBoxFor(m => m.InputValue);
            <input type="submit" value="Show Result" />
            <br />
            @Html.ValidationMessageFor(m => m.InputValue);
      
     
            <table id="menuTable2" class="gv" border="1" cellpadding="2" width="50%">
                <thead>                <tr>
                    <th>
                        Result
                    </th>
                </tr>
                </thead>                  <tbody>
                @if (@Model.lstValue != null)
                {

                    foreach (var @item in @Model.lstValue)
                    {
                        if (item == "Buzz" || item=="Wuzz")
                        {
                    <tr>
                        <td style="color: Green">
                            <span>@item.ToString()</span>
                        </td>
                    </tr>
       
                        }
                        else if (item == "Fizz" || item=="Wizz")
                        {
                    <tr>
                        <td style="color: Blue">
                            <span>@item.ToString()</span>
                        </td>
                    </tr>

                        }
                        else
                        {
                    <tr>
                        <td>
                            <span>@item.ToString()</span>
                        </td>
                    </tr>

                       
                        }


                    }
                    
                    <script type="text/javascript" language="javascript">

                        //$('tbody tr:odd', $('#menuTable2')).hide(); //hiding rows for test
                        var options = {
                            currPage: 1,
                            rowsPerPage: 20,
                            firstArrow: (new Image()).src = "../../Images/first.gif",
                            prevArrow: (new Image()).src = "../../Images/prev.gif",
                            lastArrow: (new Image()).src = "../../Images/last.gif",
                            nextArrow: (new Image()).src = "../../Images/next.gif",
                            topNav: false
                        }
                        $('#menuTable2').tablePagination(options);
</script>
                }
                  </tbody>
            </table>
           
        }
    </div>


</body>
</html>